version: "3"
services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pwgen
      - MYSQL_DATABASE=javadb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwgen

volumes:
  mysql-data:
    driver: local
