version: "3"
services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pwgen
      - MYSQL_DATABASE=javadb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwgen
    depends_on:
      - builder

  builder:
    build: .
    volumes:
      - java_app_artifacts:/app/sample-java-app/target

  tomcat:
    image: tomcat:9-alpine
    volumes:
      - java_app_artifacts:/usr/local/tomcat/webapps
    ports:
      - 80:8080
    depends_on:
      - builder
      - mysql

volumes:
  mysql-data:
  java_app_artifacts:
    driver: local
