version: "3.3"
services:
  builder:
    build:
      context: .
    depends_on:
      - mysql
    ports:
      - "80:8080"

  mysql:
    image: "mysql:5.7"
    volumes:
      - mysql-data:/var/local/mysql/data
    environment:
      -  MYSQL_USER=user
      -  MYSQL_PASSWORD=pwgen
      -  MYSQL_ROOT_PASSWORD=pwgen
      -  MYSQL_DATABASE=javadb

volumes:
    mysql-data:
